// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH2PKK19WBHAN19PZnL5NSG3N3uO4KZ6E',
    appId: '1:740500358575:web:ef23dbd5d11eb1d6875b5a',
    messagingSenderId: '740500358575',
    projectId: 'scmu-10efc',
    authDomain: 'scmu-10efc.firebaseapp.com',
    databaseURL: 'https://scmu-10efc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scmu-10efc.appspot.com',
    measurementId: 'G-F6RJC6PDDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBdQJAiyFF3oycPJJHogbMW2ss_Ik4gaU',
    appId: '1:740500358575:android:61bd359fce864cdd875b5a',
    messagingSenderId: '740500358575',
    projectId: 'scmu-10efc',
    databaseURL: 'https://scmu-10efc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scmu-10efc.appspot.com',
  );
}
